# Generated by Django 4.0 on 2021-12-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_combination_userresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='boolean',
            field=models.IntegerField(default=0),
        ),
    ]
