# Generated by Django 3.2.8 on 2021-12-26 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0007_answer_boolean'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('boolean', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dept_Combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.dept_answer')),
            ],
        ),
        migrations.CreateModel(
            name='Dept_UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_answers', models.ManyToManyField(to='application.Dept_Combination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dept_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('answers', models.ManyToManyField(to='application.Dept_Answer')),
            ],
        ),
        migrations.AddField(
            model_name='dept_combination',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.dept_question'),
        ),
    ]
