# Generated by Django 4.0 on 2021-12-27 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('application', '0008_auto_20211226_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
